### PR TITLE
Updated W1D5 tutorials

### PR DESCRIPTION
**Pull request by brian-rose**
This PR introduces the 2024 updates to the notebooks for W1D5: Introduction to Climate Modeling.

### CODE REVIEW

**Comment by iamzoltan** [comment]
hey @brian-rose, I will create a W1D5 update branch for you to make your PR.

**Review by iamzoltan — CHANGES_REQUESTED** [review]
Looks great! I changed your base branch to the W1D5-updates one I created. A few notes/task to make sure the pipeline builds smoothly:

- [x] Use the same python version as our build pipeline does (in this case, it is 3.9)
- [x] Change the number of tutorials in the materials.yml file for W1D5 from 7 to 8 (the new tutorial won't build otherwise)
- [x] Add some content for W2D1_Tutorial1 as the build expects it (its ok if this is just placeholder for now, as long as the format for the header cells match the rest of the tutorials)

Would you also add my name to the production editors list for the Tutorials?

Let me know if I can help.

**Comment by brian-rose** [comment]
> Looks great! I changed your base branch to the W1D5-updates one I created. A few notes/task to make sure the pipeline builds smoothly:
> 
> * [ ]  Use the same python version as our build pipeline does (in this case, it is 3.9)
> * [ ]  Change the number of tutorials in the materials.yml file for W1D5 from 7 to 8 (the new tutorial won't build otherwise)
> * [ ]  Add some content for W2D1_Tutorial1 as the build expects it (its ok if this is just placeholder for now, as long as the format for the header cells match the rest of the tutorials)
> 
> Would you also add my name to the production editors list for the Tutorials?
> 
> Let me know if I can help.

Hi @iamzoltan, thanks for helping to get the build going here.

I implemented the three changes you asked for. I created a local python 3.9 environment and verified that all the notebooks run properly, then removed all output again before checking them in here.

I apologize for this, but I'm afraid I don't know your name so I haven't yet added it to the list of production editors.

**Comment by iamzoltan** [comment]
@brian-rose Amazing! Great. ping you my name

**Comment by brian-rose** [comment]
> @brian-rose Amazing! Great. pinged you my name

Added to the notebooks, thanks.

**Pull request merged**
